-- MIGRACIÓN COMPLETA TEMPORAL DE PUNTAHOGAR A SUPABASE
-- Ejecuta este archivo en SQL Editor.

alter table public.properties
add column if not exists owner_token text;

create index if not exists properties_owner_token_idx
on public.properties (owner_token);

create table if not exists public.favorites (
  id bigint generated by default as identity primary key,
  device_token text not null,
  property_id bigint not null
    references public.properties(id)
    on delete cascade,
  created_at timestamptz not null default now(),
  unique (device_token, property_id)
);

create index if not exists favorites_device_token_idx
on public.favorites (device_token);

alter table public.favorites enable row level security;

grant select, insert, delete
on table public.favorites
to anon, authenticated;

grant usage, select
on sequence public.favorites_id_seq
to anon, authenticated;

drop policy if exists "Temporary favorites read"
on public.favorites;

create policy "Temporary favorites read"
on public.favorites
for select
to anon, authenticated
using (true);

drop policy if exists "Temporary favorites insert"
on public.favorites;

create policy "Temporary favorites insert"
on public.favorites
for insert
to anon, authenticated
with check (true);

drop policy if exists "Temporary favorites delete"
on public.favorites;

create policy "Temporary favorites delete"
on public.favorites
for delete
to anon, authenticated
using (true);

-- Permisos temporales para que las páginas actuales puedan leer,
-- actualizar estadísticas y administrar propiedades.
grant select, insert, update, delete
on table public.properties
to anon, authenticated;

drop policy if exists "Temporary read all properties"
on public.properties;

create policy "Temporary read all properties"
on public.properties
for select
to anon, authenticated
using (true);

drop policy if exists "Temporary insert properties"
on public.properties;

create policy "Temporary insert properties"
on public.properties
for insert
to anon, authenticated
with check (status = 'Pendiente');

drop policy if exists "Temporary update properties"
on public.properties;

create policy "Temporary update properties"
on public.properties
for update
to anon, authenticated
using (true)
with check (true);

drop policy if exists "Temporary delete properties"
on public.properties;

create policy "Temporary delete properties"
on public.properties
for delete
to anon, authenticated
using (true);

-- IMPORTANTE:
-- Estas políticas son para desarrollo.
-- Después deben reemplazarse por Supabase Auth y políticas seguras.
