-- PuntaHogar: tabla inicial de propiedades
-- Ejecuta este archivo completo desde Supabase > SQL Editor.

create table if not exists public.properties (
  id bigint generated by default as identity primary key,

  operation text not null
    check (operation in ('Alquiler', 'Venta')),

  property_type text not null,
  title text not null,
  price numeric(14, 2) not null
    check (price >= 0),

  currency text not null
    check (currency in ('RD$', 'US$')),

  bedrooms numeric(5, 1) not null default 0
    check (bedrooms >= 0),

  bathrooms numeric(5, 1) not null default 0
    check (bathrooms >= 0),

  parking integer not null default 0
    check (parking >= 0),

  meters numeric(12, 2) not null default 0
    check (meters >= 0),

  zone text not null,
  reference text,

  location_type text not null default 'aproximada'
    check (location_type in ('exacta', 'aproximada')),

  latitude double precision,
  longitude double precision,

  description text not null,

  -- Inicialmente guardaremos URLs. Más adelante se conectará Supabase Storage.
  images text[] not null default '{}',

  contact_name text not null,
  whatsapp text not null,
  email text not null,

  status text not null default 'Pendiente'
    check (status in ('Pendiente', 'Aprobada', 'Rechazada')),

  views integer not null default 0
    check (views >= 0),

  whatsapp_clicks integer not null default 0
    check (whatsapp_clicks >= 0),

  phone_clicks integer not null default 0
    check (phone_clicks >= 0),

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists properties_status_idx
  on public.properties (status);

create index if not exists properties_zone_idx
  on public.properties (zone);

create index if not exists properties_created_at_idx
  on public.properties (created_at desc);

-- Actualiza updated_at automáticamente.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_properties_updated_at
on public.properties;

create trigger set_properties_updated_at
before update on public.properties
for each row
execute function public.set_updated_at();

-- Seguridad
alter table public.properties enable row level security;

-- El visitante solo puede leer propiedades aprobadas.
drop policy if exists "Public can read approved properties"
on public.properties;

create policy "Public can read approved properties"
on public.properties
for select
to anon, authenticated
using (status = 'Aprobada');

-- El visitante puede enviar una propiedad únicamente como Pendiente.
drop policy if exists "Public can submit pending properties"
on public.properties;

create policy "Public can submit pending properties"
on public.properties
for insert
to anon, authenticated
with check (status = 'Pendiente');

grant select, insert on table public.properties
to anon, authenticated;

grant usage, select on sequence public.properties_id_seq
to anon, authenticated;

-- No se otorgan permisos públicos de UPDATE ni DELETE.
-- Esas acciones se conectarán después mediante autenticación administrativa real.
